version: "3"
services:

  emit:
    build: .
    ports:
      - "8080:8080"
    links:
      - nginx
    depends_on:
      - nginx
    command: /app/emit
    environment:
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

