version: "3"
services:

  emit:
    build: .
    ports:
      - "8080:8080"
    links:
      - nginx
    depends_on:
      - nginx
    environment:
      - B2_ACCOUNT_ID
      - B2_ACCOUNT_KEY

  nginx:
    build: ./nginx/
    ports:
      - "80:80"

